[package]
name = "scripts-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.1"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
